### ISSUE TITLE
Facing some issue for kd-icon on firefox/safari, Working fine for Chorme

### ISSUE THREAD

**Issue by ashishpawar12** [kyndryl-design-system/shidoka-foundation#28]
**Describe the bug**

We have implemented Shidoka design. But on runtime we are getting error as below

<img width="1420" alt="image" src="https://github.com/kyndryl-design-system/shidoka-foundation/assets/18259137/cb35293a-e562-4f00-996b-0a64f9fd7363">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Browser [e.g. firefox]
- Version [e.g. 122.0.1]

**Comment by ashishpawar12** [comment]
This is working fine on chrome. We have two different bundle with same kd-icon import. Somehow Chrome is successfully overwriting element but not firefox. We can have a call to understand better
And i have came across this article too.
https://pawelpsztyc.medium.com/building-web-components-for-multi-tenant-environments-e3b67b426113

**Comment by ashishpawar12** [comment]
We have Kyndryl bridge project where we have multiple component loading. Into that multiple bundle we have same import for webcomponent is there. We have also given unique webpack name to bundle. Chrome is smart enough to differentiate but not firefox.

**Comment by ashishpawar12** [comment]
Issue has been only with internal import link with kd-icon. Other Shidoka component import is working fine with firefox too
<img width="1420" alt="image" src="https://github.com/kyndryl-design-system/shidoka-foundation/assets/18259137/187329cc-0d8d-4b9e-ab10-4ec493d703a6">

<img width="1420" alt="image" src="https://github.com/kyndryl-design-system/shidoka-foundation/assets/18259137/b71e36c7-8422-4689-a939-7c272e6997f6">
Not have icon import
<img width="1420" alt="image" src="https://github.com/kyndryl-design-system/shidoka-foundation/assets/18259137/06cf3764-8135-4092-9d68-754a08cfa234">
Have icon import
<img width="1420" alt="image" src="https://github.com/kyndryl-design-system/shidoka-foundation/assets/18259137/a973b9a7-17ef-4286-8166-e25bd8ab4b54">

**Comment by ashishpawar12** [comment]
Have a suggestion why we don't ask application to import icon rather than importing internally? Is this not possible?

**Comment by ashishpawar12** [comment]
after removing below kd-icon highilghted code it worked on firefox. As its taking icon class definition from other bundle. Need to see how we can avoid same internal import for 2 different bundle or ask application to add import at bundle level.

Internal import has only issue once both bundle will be coming to same page.

<img width="1420" alt="image" src="https://github.com/kyndryl-design-system/shidoka-foundation/assets/18259137/e1d2ca05-9496-4266-9ef1-85aecba46338">

<img width="1420" alt="image" src="https://github.com/kyndryl-design-system/shidoka-foundation/assets/18259137/832bdb91-2248-459d-8058-f74ace3103f0">

**Comment by brian-patrick-3** [comment]
Please see the README which contains all of the information I have regarding this error: https://github.com/kyndryl-design-system/shidoka-applications?tab=readme-ov-file#handling-failed-to-execute-define-on-customelementregistry

**Comment by ashishpawar12** [comment]
Thanks @brian-patrick-3 . Will try for rollup example. And have tried other workaround mention on same readme file but that is not working.

Just one question on final minified js i can remove import using rollup js? Or for whole final build i need to replace with rollup js

**Comment by brian-patrick-3** [comment]
Rollup is just what we use to bundle the Shidoka libraries.
